kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
      zookeeper: localhost:2181
      schemaRegistry: http://localhost:8085
      kafkaConnect:
        - name: first
          address: http://localhost:8083
      jmxPort: 9997
      bufRegistry: ""
      bufPort: 0
      bufApiToken: ""
      bufDefaultOwner: ""
      bufOwnerRepoByProtobufMessageName:
        fully.qualified.type.1: "owner/repo"
        fully.qualified.type.2: "owner/repo"
      protobufMessageNameByTopic:
        topic.1: fully.qualified.type.1
        topic.2: fully.qualified.type.2
      protobufKeyMessageNameByTopic:
        topic.1: fully.qualified.type.1
        topic.2: fully.qualified.type.2
spring:
  jmx:
    enabled: true
auth:
  type: DISABLED
